
package tests

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/kexas-project/kexas/ktest/report"
)

// ========================================
// HTML GENERATION TESTS
// ========================================

// TestGenerate_CreatesFile verifies that Generate creates the HTML file.
func TestGenerate_CreatesFile(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "test-report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "TestProject",
		Timestamp:   time.Now(),
		Duration:    5 * time.Second,
		Suites: []report.TestSuiteResult{
			{
				Name: "auth",
				Tests: []report.TestCaseResult{
					{Name: "TestLogin", Status: report.StatusPassed, Duration: 2 * time.Second},
					{Name: "TestLogout", Status: report.StatusFailed, Duration: 3 * time.Second, ErrorMsg: "assert failed"},
				},
			},
		},
		Workers: 1,
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var info os.FileInfo
	info, err = os.Stat(outputPath)
	if err != nil {
		t.Fatalf("report file not created: %v", err)
	}
	if info.Size() == 0 {
		t.Error("report file is empty")
	}
}

// TestGenerateFiles_CreatesVersionedCopy verifies base + archive files exist.
func TestGenerateFiles_CreatesVersionedCopy(t *testing.T) {
	var tmpDir string = t.TempDir()
	var fixedTime time.Time = time.Date(2026, time.February, 27, 20, 30, 0, 0, time.UTC)

	var r *report.TestReport = &report.TestReport{
		ProjectName: "Versioned",
		Timestamp:   fixedTime,
	}
	r.ComputeStats()

	var basePath string
	var versionedPath string
	var err error
	basePath, versionedPath, err = report.GenerateFiles(r, tmpDir)
	if err != nil {
		t.Fatalf("GenerateFiles failed: %v", err)
	}

	if basePath != filepath.Join(tmpDir, "report.html") {
		t.Errorf("unexpected base path: %s", basePath)
	}
	if _, statErr := os.Stat(basePath); statErr != nil {
		t.Fatalf("base report not created: %v", statErr)
	}
	if _, statErr := os.Stat(versionedPath); statErr != nil {
		t.Fatalf("versioned report not created: %v", statErr)
	}
	if !strings.Contains(filepath.Base(versionedPath), "report-20260227-203000") {
		t.Errorf("versioned filename missing timestamp, got %s", versionedPath)
	}
}

// TestGenerateFiles_CollisionAddsSuffix verifies suffix increments on collisions.
func TestGenerateFiles_CollisionAddsSuffix(t *testing.T) {
	var tmpDir string = t.TempDir()
	var fixedTime time.Time = time.Date(2026, time.February, 27, 20, 30, 0, 0, time.UTC)

	createReport := func(run int) string {
		var r *report.TestReport = &report.TestReport{
			ProjectName: fmt.Sprintf("Run%d", run),
			Timestamp:   fixedTime,
		}
		r.ComputeStats()

		var _, versionedPath string
		var err error
		_, versionedPath, err = report.GenerateFiles(r, tmpDir)
		if err != nil {
			t.Fatalf("GenerateFiles failed: %v", err)
		}
		return versionedPath
	}

	var first string = createReport(1)
	var second string = createReport(2)
	if filepath.Base(first) != "report-20260227-203000.html" {
		t.Errorf("unexpected first filename: %s", filepath.Base(first))
	}
	if filepath.Base(second) != "report-20260227-203000-001.html" {
		t.Errorf("expected -001 suffix for second file, got %s", filepath.Base(second))
	}
}

// TestGenerate_ContainsHTML verifies that the generated file contains expected HTML.
func TestGenerate_ContainsHTML(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "KexasProject",
		Timestamp:   time.Now(),
		Duration:    10 * time.Second,
		Suites: []report.TestSuiteResult{
			{
				Name: "signin_tests",
				Tests: []report.TestCaseResult{
					{Name: "TestLogin", Status: report.StatusPassed, Duration: time.Second},
				},
			},
		},
		Workers: 2,
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var content string = string(data)

	// Check for key HTML elements
	var checks []string = []string{
		"<!DOCTYPE html>",
		"KexasProject",
		"data-theme=\"dark\"",
		"theme-toggle",
		"signin_tests",
		"TestLogin",
		"passed",
		"search-input",
		"filter-btn",
		"Generated by",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("report HTML missing expected content: %q", check)
		}
	}
}

// TestGenerate_ContainsDarkLightCSS verifies both theme variables exist.
func TestGenerate_ContainsDarkLightCSS(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "ThemeTest",
		Timestamp:   time.Now(),
		Suites:      []report.TestSuiteResult{},
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var content string = string(data)

	if !strings.Contains(content, ":root") {
		t.Error("report missing :root CSS (dark theme defaults)")
	}
	if !strings.Contains(content, "[data-theme=\"light\"]") {
		t.Error("report missing light theme CSS variables")
	}
}

// TestGenerate_ErrorMessage verifies failed test error messages appear.
func TestGenerate_ErrorMessage(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "ErrTest",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{
						Name:     "TestBroken",
						Status:   report.StatusFailed,
						ErrorMsg: "expected 200 got 500",
					},
				},
			},
		},
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}

	if !strings.Contains(string(data), "expected 200 got 500") {
		t.Error("report should contain the error message for failed tests")
	}
}

// TestGenerate_WorkerTags verifies worker tags show when workers > 1.
func TestGenerate_WorkerTags(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "ParallelTest",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{Name: "T1", Status: report.StatusPassed, WorkerID: 0},
					{Name: "T2", Status: report.StatusPassed, WorkerID: 1},
				},
			},
		},
		Workers: 2,
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}

	if !strings.Contains(string(data), "W0") {
		t.Error("report should contain worker tag W0")
	}
	if !strings.Contains(string(data), "W1") {
		t.Error("report should contain worker tag W1")
	}
}

// TestGenerate_NoWorkerTagsWhenSingle verifies no worker tags for sequential.
func TestGenerate_NoWorkerTagsWhenSingle(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "SeqTest",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{Name: "T1", Status: report.StatusPassed, WorkerID: 0},
				},
			},
		},
		Workers: 1,
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}

	// Check that no worker tag spans are rendered (CSS class definition is OK)
	if strings.Contains(string(data), "<span class=\"worker-tag\">") {
		t.Error("report should NOT render worker tag spans when Workers=1")
	}
}

// TestGenerate_CreatesSubdirectories verifies nested output paths work.
func TestGenerate_CreatesSubdirectories(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "deep", "nested", "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "Deep",
		Timestamp:   time.Now(),
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate should create subdirectories, got: %v", err)
	}
	if _, statErr := os.Stat(outputPath); os.IsNotExist(statErr) {
		t.Error("report file not created in nested directory")
	}
}

// TestGenerate_InsightsSection verifies donut and duration widgets render.
func TestGenerate_InsightsSection(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "Insights",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{Name: "suite.TestSlow", Status: report.StatusFailed, Duration: 4 * time.Second},
					{Name: "suite.TestMedium", Status: report.StatusPassed, Duration: 2 * time.Second},
					{Name: "suite.TestSkipped", Status: report.StatusSkipped, Duration: 0},
				},
			},
		},
	}
	r.ComputeStats()

	if err := report.Generate(r, outputPath); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	var err error
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var html string = string(data)

	var mustContain []string = []string{
		"Outcome mix",
		"Slowest tests",
		"class=\"donut\"",
		"class=\"duration-list\"",
		"legend-dot pass",
		"legend-dot fail",
		"legend-dot skip",
	}
	for _, token := range mustContain {
		if !strings.Contains(html, token) {
			t.Fatalf("report missing insights token %q", token)
		}
	}

	var slowIdx int = strings.Index(html, "suite.TestSlow")
	var mediumIdx int = strings.Index(html, "suite.TestMedium")
	if slowIdx == -1 || mediumIdx == -1 {
		t.Fatalf("slow or medium test missing in duration list")
	}
	if slowIdx > mediumIdx {
		t.Fatalf("expected slowest test to appear before medium, got indices %d > %d", slowIdx, mediumIdx)
	}
}

// TestInsights_AllPassDonut verifies donut shows 100% pass when all tests pass.
func TestInsights_AllPassDonut(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "AllPass",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{Name: "TestA", Status: report.StatusPassed, Duration: 1 * time.Second},
					{Name: "TestB", Status: report.StatusPassed, Duration: 2 * time.Second},
				},
			},
		},
	}
	r.ComputeStats()

	if err := report.Generate(r, outputPath); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	var err error
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var html string = string(data)

	// Donut center should show 100%
	if !strings.Contains(html, "100%") {
		t.Error("expected 100% pass in donut center")
	}
	// Legend should show 2 passed, 0 failed, 0 skipped
	if !strings.Contains(html, "<strong>2</strong>") {
		t.Error("expected passed count of 2 in legend")
	}
}

// TestInsights_AllFailDonut verifies donut shows 0% pass when all tests fail.
func TestInsights_AllFailDonut(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "AllFail",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{Name: "TestX", Status: report.StatusFailed, Duration: 1 * time.Second},
					{Name: "TestY", Status: report.StatusFailed, Duration: 500 * time.Millisecond},
				},
			},
		},
	}
	r.ComputeStats()

	if err := report.Generate(r, outputPath); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	var err error
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var html string = string(data)

	// Donut center should show 0%
	if !strings.Contains(html, "0%") {
		t.Error("expected 0% pass in donut center when all tests fail")
	}
	// Legend should show 0 passed, 2 failed
	if !strings.Contains(html, "<strong>0</strong>") {
		t.Error("expected passed count of 0 in legend")
	}
}

// TestInsights_NoTests_EmptyState verifies duration card shows empty message.
func TestInsights_NoTests_EmptyState(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "Empty",
		Timestamp:   time.Now(),
		Suites:      []report.TestSuiteResult{},
	}
	r.ComputeStats()

	if err := report.Generate(r, outputPath); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	var err error
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var html string = string(data)

	if !strings.Contains(html, "No tests executed") {
		t.Error("expected 'No tests executed' message in duration card when no tests exist")
	}
}

// TestInsights_SingleTest_DurationBar verifies bar width is 100% for a single test.
func TestInsights_SingleTest_DurationBar(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "Single",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{Name: "TestOnly", Status: report.StatusPassed, Duration: 3 * time.Second},
				},
			},
		},
	}
	r.ComputeStats()

	if err := report.Generate(r, outputPath); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	var err error
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var html string = string(data)

	// Single test should have width 100%
	if !strings.Contains(html, "width:100.00%") {
		t.Error("expected single test duration bar to be 100% width")
	}
	if !strings.Contains(html, "TestOnly") {
		t.Error("expected test name 'TestOnly' in duration list")
	}
}

// TestInsights_ZeroDuration_NoPanic verifies no division-by-zero when all durations are 0.
func TestInsights_ZeroDuration_NoPanic(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "ZeroDur",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{Name: "TestZeroA", Status: report.StatusPassed, Duration: 0},
					{Name: "TestZeroB", Status: report.StatusPassed, Duration: 0},
				},
			},
		},
	}
	r.ComputeStats()

	// Should not panic on zero durations
	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed with zero durations: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var html string = string(data)

	// Duration list should still render (with minimum bar widths)
	if !strings.Contains(html, "duration-list") {
		t.Error("expected duration-list to render even with zero durations")
	}
}

// TestInsights_DurationSortOrder verifies slowest tests appear first in the list.
func TestInsights_DurationSortOrder(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "SortOrder",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{Name: "TestFast", Status: report.StatusPassed, Duration: 100 * time.Millisecond},
					{Name: "TestSlowest", Status: report.StatusFailed, Duration: 10 * time.Second},
					{Name: "TestMid", Status: report.StatusPassed, Duration: 1 * time.Second},
				},
			},
		},
	}
	r.ComputeStats()

	if err := report.Generate(r, outputPath); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	var err error
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var html string = string(data)

	var slowIdx int = strings.Index(html, "TestSlowest")
	var midIdx int = strings.Index(html, "TestMid")
	var fastIdx int = strings.Index(html, "TestFast")

	if slowIdx == -1 || midIdx == -1 || fastIdx == -1 {
		t.Fatal("one or more test names missing from duration list")
	}
	if slowIdx > midIdx {
		t.Errorf("TestSlowest should appear before TestMid (indices: %d > %d)", slowIdx, midIdx)
	}
	if midIdx > fastIdx {
		t.Errorf("TestMid should appear before TestFast (indices: %d > %d)", midIdx, fastIdx)
	}
}

// ========================================
// UTILITY TESTS
// ========================================

// TestProjectNameFromDir_Normal verifies extracting project name.
func TestProjectNameFromDir_Normal(t *testing.T) {
	var name string = report.ProjectNameFromDir("/Users/dev/projects/saucelab")
	if name != "saucelab" {
		t.Errorf("expected 'saucelab', got %q", name)
	}
}

// TestProjectNameFromDir_Dot verifies fallback for current directory.
func TestProjectNameFromDir_Dot(t *testing.T) {
	var name string = report.ProjectNameFromDir(".")
	if name != "kexas" {
		t.Errorf("expected 'kexas', got %q", name)
	}
}

// TestProjectNameFromDir_Root verifies fallback for root path.
func TestProjectNameFromDir_Root(t *testing.T) {
	var name string = report.ProjectNameFromDir("/")
	if name != "kexas" {
		t.Errorf("expected 'kexas', got %q", name)
	}
}

// TestHTMLEscaping verifies that test names with special chars are escaped.
func TestHTMLEscaping(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "Escape<Test>&\"Project\"",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{Name: "Test<XSS>", Status: report.StatusPassed},
				},
			},
		},
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var content string = string(data)

	// Raw < should NOT appear in project name or test name (must be escaped)
	if strings.Contains(content, "Escape<Test>") {
		t.Error("project name should be HTML-escaped, found unescaped < >")
	}
	if strings.Contains(content, "Test<XSS>") {
		t.Error("test name should be HTML-escaped, found unescaped < >")
	}
	// But the escaped versions should be present
	if !strings.Contains(content, "Escape&lt;Test&gt;") {
		t.Error("project name should contain HTML-escaped version")
	}
}
