
package ktest_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/jankylewis/kexas/ktest/report"
)

// ========================================
// HTML GENERATION TESTS
// ========================================

// TestGenerate_CreatesFile verifies that Generate creates the HTML file.
func TestGenerate_CreatesFile(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "test-report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "TestProject",
		Timestamp:   time.Now(),
		Duration:    5 * time.Second,
		Suites: []report.TestSuiteResult{
			{
				Name: "auth",
				Tests: []report.TestCaseResult{
					{Name: "TestLogin", Status: report.StatusPassed, Duration: 2 * time.Second},
					{Name: "TestLogout", Status: report.StatusFailed, Duration: 3 * time.Second, ErrorMsg: "assert failed"},
				},
			},
		},
		Workers: 1,
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var info os.FileInfo
	info, err = os.Stat(outputPath)
	if err != nil {
		t.Fatalf("report file not created: %v", err)
	}
	if info.Size() == 0 {
		t.Error("report file is empty")
	}
}

// TestGenerateFiles_CreatesVersionedCopy verifies base + archive files exist.
func TestGenerateFiles_CreatesVersionedCopy(t *testing.T) {
	var tmpDir string = t.TempDir()
	var fixedTime time.Time = time.Date(2026, time.February, 27, 20, 30, 0, 0, time.UTC)

	var r *report.TestReport = &report.TestReport{
		ProjectName: "Versioned",
		Timestamp:   fixedTime,
	}
	r.ComputeStats()

	var basePath string
	var versionedPath string
	var err error
	basePath, versionedPath, err = report.GenerateFiles(r, tmpDir)
	if err != nil {
		t.Fatalf("GenerateFiles failed: %v", err)
	}

	if basePath != filepath.Join(tmpDir, "report.html") {
		t.Errorf("unexpected base path: %s", basePath)
	}
	if _, statErr := os.Stat(basePath); statErr != nil {
		t.Fatalf("base report not created: %v", statErr)
	}
	if _, statErr := os.Stat(versionedPath); statErr != nil {
		t.Fatalf("versioned report not created: %v", statErr)
	}
	if !strings.Contains(filepath.Base(versionedPath), "report-20260227-203000") {
		t.Errorf("versioned filename missing timestamp, got %s", versionedPath)
	}
}

// TestGenerateFiles_CollisionAddsSuffix verifies suffix increments on collisions.
func TestGenerateFiles_CollisionAddsSuffix(t *testing.T) {
	var tmpDir string = t.TempDir()
	var fixedTime time.Time = time.Date(2026, time.February, 27, 20, 30, 0, 0, time.UTC)

	var createReport func(int) string = func(run int) string {
		var r *report.TestReport = &report.TestReport{
			ProjectName: fmt.Sprintf("Run%d", run),
			Timestamp:   fixedTime,
		}
		r.ComputeStats()

		var _, versionedPath string
		var err error
		_, versionedPath, err = report.GenerateFiles(r, tmpDir)
		if err != nil {
			t.Fatalf("GenerateFiles failed: %v", err)
		}
		return versionedPath
	}

	var first string = createReport(1)
	var second string = createReport(2)
	if filepath.Base(first) != "report-20260227-203000.html" {
		t.Errorf("unexpected first filename: %s", filepath.Base(first))
	}
	if filepath.Base(second) != "report-20260227-203000-001.html" {
		t.Errorf("expected -001 suffix for second file, got %s", filepath.Base(second))
	}
}

// TestGenerate_ContainsHTML verifies that the generated file contains expected HTML.
func TestGenerate_ContainsHTML(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "KexasProject",
		Timestamp:   time.Now(),
		Duration:    10 * time.Second,
		Suites: []report.TestSuiteResult{
			{
				Name: "signin_tests",
				Tests: []report.TestCaseResult{
					{Name: "TestLogin", Status: report.StatusPassed, Duration: time.Second},
				},
			},
		},
		Workers: 2,
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var content string = string(data)

	// Check for key HTML elements
	var checks []string = []string{
		"<!DOCTYPE html>",
		"KexasProject",
		"data-theme=\"dark\"",
		"theme-toggle",
		"signin_tests",
		"TestLogin",
		"passed",
		"search-input",
		"filter-btn",
		"Generated by",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("report HTML missing expected content: %q", check)
		}
	}
}

// TestGenerate_ContainsDarkLightCSS verifies both theme variables exist.
func TestGenerate_ContainsDarkLightCSS(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "ThemeTest",
		Timestamp:   time.Now(),
		Suites:      []report.TestSuiteResult{},
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}
	var content string = string(data)

	if !strings.Contains(content, ":root") {
		t.Error("report missing :root CSS (dark theme defaults)")
	}
	if !strings.Contains(content, "[data-theme=\"light\"]") {
		t.Error("report missing light theme CSS variables")
	}
}

// TestGenerate_ErrorMessage verifies failed test error messages appear.
func TestGenerate_ErrorMessage(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "ErrTest",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{
						Name:     "TestBroken",
						Status:   report.StatusFailed,
						ErrorMsg: "expected 200 got 500",
					},
				},
			},
		},
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}

	if !strings.Contains(string(data), "expected 200 got 500") {
		t.Error("report should contain the error message for failed tests")
	}
}

// TestGenerate_WorkerTags verifies worker tags show when workers > 1.
func TestGenerate_WorkerTags(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "ParallelTest",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{Name: "T1", Status: report.StatusPassed, WorkerID: 0},
					{Name: "T2", Status: report.StatusPassed, WorkerID: 1},
				},
			},
		},
		Workers: 2,
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}

	if !strings.Contains(string(data), "W0") {
		t.Error("report should contain worker tag W0")
	}
	if !strings.Contains(string(data), "W1") {
		t.Error("report should contain worker tag W1")
	}
}

// TestGenerate_NoWorkerTagsWhenSingle verifies no worker tags for sequential.
func TestGenerate_NoWorkerTagsWhenSingle(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "SeqTest",
		Timestamp:   time.Now(),
		Suites: []report.TestSuiteResult{
			{
				Name: "suite",
				Tests: []report.TestCaseResult{
					{Name: "T1", Status: report.StatusPassed, WorkerID: 0},
				},
			},
		},
		Workers: 1,
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	var data []byte
	data, err = os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read report: %v", err)
	}

	// Check that no worker tag spans are rendered (CSS class definition is OK)
	if strings.Contains(string(data), "<span class=\"worker-tag\">") {
		t.Error("report should NOT render worker tag spans when Workers=1")
	}
}

// TestGenerate_CreatesSubdirectories verifies nested output paths work.
func TestGenerate_CreatesSubdirectories(t *testing.T) {
	var tmpDir string = t.TempDir()
	var outputPath string = filepath.Join(tmpDir, "deep", "nested", "report.html")

	var r *report.TestReport = &report.TestReport{
		ProjectName: "Deep",
		Timestamp:   time.Now(),
	}
	r.ComputeStats()

	var err error = report.Generate(r, outputPath)
	if err != nil {
		t.Fatalf("Generate should create subdirectories, got: %v", err)
	}
	if _, statErr := os.Stat(outputPath); os.IsNotExist(statErr) {
		t.Error("report file not created in nested directory")
	}
}
