package report

import (
	"fmt"
	"html"
	"strings"
)

// buildHTML assembles the complete HTML document from the report data.
func buildHTML(r *TestReport) string {
	var b strings.Builder
	b.Grow(16384)

	writeDocOpen(&b)
	writeHeader(&b, r)
	writeSummaryCards(&b, r)
	writeProgressBar(&b, r)
	writeInsights(&b, r)
	writeToolbar(&b, r)
	writeSuites(&b, r)
	writeFooter(&b, r)
	writeDocClose(&b)

	return b.String()
}

// writeDocOpen writes the HTML head section with embedded CSS.
func writeDocOpen(b *strings.Builder) {
	b.WriteString("<!DOCTYPE html>\n<html lang=\"en\" data-theme=\"dark\">\n<head>\n")
	b.WriteString("<meta charset=\"UTF-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
	b.WriteString("<title>Kexas Test Report</title>\n")
	b.WriteString("<style>")
	b.WriteString(reportCSS)
	b.WriteString("</style>\n</head>\n<body>\n<div class=\"container\">\n")
}

// writeHeader writes the report title and theme toggle button.
func writeHeader(b *strings.Builder, r *TestReport) {
	b.WriteString("<button id=\"theme-toggle\" class=\"theme-toggle\" aria-label=\"Toggle theme\"></button>\n")
	b.WriteString("<div class=\"header\">\n")
	fmt.Fprintf(b, "<h1>%s</h1>\n", html.EscapeString(r.ProjectName))
	fmt.Fprintf(b, "<div class=\"subtitle\">%s</div>\n",
		r.Timestamp.Format("January 2, 2006 at 3:04 PM"))
	b.WriteString("</div>\n")
}

// writeSummaryCards renders the 4 stat cards (total, passed, failed, skipped).
func writeSummaryCards(b *strings.Builder, r *TestReport) {
	b.WriteString("<div class=\"summary\">\n")
	writeStatCard(b, "total", "Tests", r.TotalTests)
	writeStatCard(b, "passed", "Passed", r.Passed)
	writeStatCard(b, "failed", "Failed", r.Failed)
	writeStatCard(b, "skipped", "Skipped", r.Skipped)
	b.WriteString("</div>\n")
}

// writeStatCard renders a single stat card.
func writeStatCard(b *strings.Builder, class string, label string, value int) {
	fmt.Fprintf(b, "<div class=\"stat-card %s\">\n", class)
	fmt.Fprintf(b, "<div class=\"stat-value\">%d</div>\n", value)
	fmt.Fprintf(b, "<div class=\"stat-label\">%s</div>\n", label)
	b.WriteString("</div>\n")
}

// writeProgressBar renders the pass/fail/skip progress bar with pass rate.
func writeProgressBar(b *strings.Builder, r *TestReport) {
	b.WriteString("<div class=\"progress-bar-container\">\n")
	b.WriteString("<div class=\"progress-bar-header\">\n")
	fmt.Fprintf(b, "<span class=\"pass-rate\">%.1f%% passed</span>\n", r.PassRate)
	b.WriteString("</div>\n")

	var passW float64 = safePercent(r.Passed, r.TotalTests)
	var failW float64 = safePercent(r.Failed, r.TotalTests)
	var skipW float64 = safePercent(r.Skipped, r.TotalTests)

	b.WriteString("<div class=\"progress-bar\">\n")
	fmt.Fprintf(b, "<div class=\"bar-pass\" style=\"width:%.2f%%\"></div>\n", passW)
	fmt.Fprintf(b, "<div class=\"bar-fail\" style=\"width:%.2f%%\"></div>\n", failW)
	fmt.Fprintf(b, "<div class=\"bar-skip\" style=\"width:%.2f%%\"></div>\n", skipW)
	b.WriteString("</div>\n</div>\n")
}

// writeFooter writes the report footer with branding.
func writeFooter(b *strings.Builder, r *TestReport) {
	b.WriteString("<div class=\"footer\">\n")
	fmt.Fprintf(b, "Generated by <a href=\"#\">Kexas</a> on %s\n",
		r.Timestamp.Format("2006-01-02 15:04:05"))
	b.WriteString("</div>\n")
}

// writeDocClose writes the closing tags and embedded JavaScript.
func writeDocClose(b *strings.Builder) {
	b.WriteString("</div>\n") // close container
	b.WriteString("<script>")
	b.WriteString(reportJS)
	b.WriteString("</script>\n")
	b.WriteString("</body>\n</html>\n")
}
